spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  security:
    user:
      name: user
      password: password

server:
  error:
    whitelabel:
      enabled: false
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: ERROR

mail:
  host: smtp.gmail.com
  port: 587
  username: your-email@gmail.com
  password: your-app-specific-password
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB

upload:
  path: uploads

messages:
  basename: messages
  encoding: UTF-8
  en:
    site:
      title: CarHub - Your Ultimate Car Destination
      logo: CarHub
    nav:
      home: Home
      featured: Featured Cars
      about: About Us
      login: Login
      signup: Sign Up
    hero:
      title: Welcome to CarHub
      subtitle: Discover Your Dream Car Today
      cta: Explore Cars
    featured:
      title: Featured Cars
    car1:
      title: Luxury Sedan
      description: Experience ultimate comfort and style
    about:
      title: About CarHub
      description: CarHub is your one-stop destination for all things automotive...
    footer:
      copyright: © 2023 CarHub. All rights reserved.

main:
  allow-bean-definition-overriding: true